[build]
  publish = "dist/iscar-auth" # Update this to the path of your Angular app's build output folder



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



[functions]
  directory = "my_functions" # Upd
